services:
  pg_chainlink:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /Users/jerryc.quiles/desktop/github/chainlink/.chainlink-rinkeby/data:/var/lib/postgressql/data/
    env_file:
      - database.env
  chainlink:
    image: "smartcontract/chainlink:1.3.0"
    env_file:
      - .env
    depends_on:
      - pg_chainlink
    ports:
      - "6688:6688"
    volumes:
      - /Users/jerryc.quiles/desktop/github/chainlink/.chainlink-rinkeby/chainlink-volume:/chainlink/
    command: node start --password /chainlink/password.txt --api /chainlink/apicredentials.txt   
